### ISSUE TITLE
使用table表格排序功能时order属性没有作用，大佬是因为什么

### ISSUE THREAD

**Issue by 1931602950** [un-pany/v3-admin-vite#100]
直接复制elementplus上的案列过来是可以的，但是数据要是请求过来的就不生效，我在你的table中用创建时间试了排序好像也不行。sort是数字，prop也有。就是不生效搞不懂为什么

**Comment by pany-ang** [comment]
如果是 Element Plus 的问题，可以去它的仓库提交 Issue 哦！
