### ISSUE TITLE
Static resources mapping  issue in packaging process

### ISSUE THREAD

**Issue by DDDPG** [un-pany/v3-admin-vite#103]
When packaging, in `vite.config.ts`, import the env `VITE_PUBLIC_PATH` as public basic dir, but the static resource in `dist` folder did not changed correspondingly, because `assetsDir` was “static”, which is static, I think it is supposed to be `VITE_PUBLIC_PATH.slice(1, -1)` then the path mapping is right. From my point of view this is more convinent than memorizing the static mapping rules in DockerFIle or other files.

Apology for the  interruption few days ago of merging request issue.🏳️

**Comment by pany-ang** [comment]
"assetsDir" doesn't seem to need to be synchronized with "VITE_PUBLIC_PATH". I don't particularly understand the scenario you mentioned
