### ISSUE TITLE
在配置面板设置隐藏标签栏时，logo会变小

### ISSUE THREAD

**Issue by WingLeoo** [un-pany/v3-admin-vite#109]
有标签栏时
![image](https://github.com/un-pany/v3-admin-vite/assets/57828100/e6f14742-ac1e-46f4-8a95-3e93391e1ae1)
没有标签栏时
![image](https://github.com/un-pany/v3-admin-vite/assets/57828100/53094b56-1917-41b3-ab21-facaf98b80c6)

可以看到logo图片变小了，4.x 版本就是这么设计的吗？

**Comment by pany-ang** [comment]
yes，设计如此：logo 区域的高度和右边 header 同步

**Comment by WingLeoo** [comment]
> yes，设计如此：logo 区域的高度和右边 header 同步
ok
