### ISSUE TITLE
修改任意界面，切换其他界面就会出现空白，必须要手动重新刷新才可以出现界面

### ISSUE THREAD

**Issue by AuroraWei** [un-pany/v3-admin-vite#114]
修改任意界面，切换其他界面就会出现空白，必须要手动重新刷新才可以出现界面

![bdf0b](https://github.com/un-pany/v3-admin-vite/assets/39292068/797262ad-4e15-419f-bdef-09dc9b7f06af)

**Comment by pany-ang** [comment]
https://github.com/un-pany/v3-admin-vite/issues/101

**Comment by pany-ang** [comment]
如果你能优化这一点，欢迎 PR 共建项目~

**Comment by AuroraWei** [comment]
应该不是这个问题，控制台没有报错. 而且我是直接拉代码下来，几乎还没做什么修改，只是在首页打印一个console.log，当时可以显示，切换一下菜单就所有的页面都没有了。（我还检查了一下页面，所有的是跟vue2的写法一样）

**Comment by pany-ang** [comment]
那你可以用我的预览地址或者拉一份新的代码测试，如果不能复现你说的情况，那就还是你改动后的代码有问题，并且这种情况目前为止都是因为没有保证一个根元素导致的

**Comment by AuroraWei** [comment]
还是不行，我只是在首页添加了一个这个，我也很奇怪其他人没有遇见这个问题吗
![6e31267e](https://github.com/un-pany/v3-admin-vite/assets/39292068/3f1dd4e3-6fea-4f73-89df-3385fabba97e)

**Comment by AuroraWei** [comment]
![5-05-55](https://github.com/un-pany/v3-admin-vite/assets/39292068/b4dc7df7-6ec4-4634-a559-0c3a3a9d88aa)
就是这样，它也不报错

**Comment by AuroraWei** [comment]
我就加了给你截图的那个·

**Comment by pany-ang** [comment]
你建一个仓库，把你代码推上去看看

**Comment by pany-ang** [comment]
再说明一下你的环境，node 版本、浏览器版本等

**Comment by AuroraWei** [comment]
node是18.16，浏览器Chrome116

**Comment by pany-ang** [comment]
> node是18.16，浏览器Chrome116

这个不会有问题，只能上次代码给我复现了

**Comment by AuroraWei** [comment]
这个代码真的就是你的代码

**Comment by pany-ang** [comment]
我这边复现不了，就不能帮你解决问题... 预览环境你自己能复现吗？https://un-pany.github.io/v3-admin-vite/#/dashboard

**Comment by AuroraWei** [comment]
https://gitee.com/mouyalin/v3-admin-vite.git我把代码传到这里了，你拉下来试一下吧

**Comment by pany-ang** [comment]
> https://gitee.com/mouyalin/v3-admin-vite.git 我把代码传到这里了，你拉下来试一下吧

不能复现... 这份代码没问题

**Comment by w871507855** [comment]
@AuroraWei 在src/App.vue里面修改下代码试试，在<route-view :key="$route.path">
<template>
  <ElConfigProvider :locale="zhCn">
    <router-view :key="$route.path" />
  </ElConfigProvider>
</template>

**Comment by pany-ang** [comment]
> https://gitee.com/mouyalin/v3-admin-vite.git 我把代码传到这里了，你拉下来试一下吧

已复现，需要修改一下 TS 代码热更新后才能触发你说的问题

**Comment by pany-ang** [comment]
复现步骤：

1. 进入一个页面
2. 去修改该页面的 TS 代码
3. 回到浏览器切换页面
4. 内容区空白了

**Comment by AuroraWei** [comment]
可以修复吗

**Comment by AuroraWei** [comment]
因该是热更新的问题吧

**Comment by AuroraWei** [comment]
![6e31267e](https://github.com/un-pany/v3-admin-vite/assets/39292068/051be064-48c6-4265-aa02-6cbac3a1c1ac)
这样也可以，不要它的动画

**Comment by pany-ang** [comment]
有可能是 vue 本身的问题：https://github.com/vuejs/core/issues/7121

**Comment by pany-ang** [comment]
已修复该问题，代码已更新：https://github.com/un-pany/v3-admin-vite/commit/db3de00fcfbba52d6c3a6bb478654be0afae297a
