### ISSUE TITLE
维护计划

### ISSUE THREAD

**Issue by pany-ang** [un-pany/v3-admin-vite#12]
_不一定全都要实现，因为还是想继续将这个项目定义为**最小的后台管理系统**解决方案，所以不会添加太多功能进去_

**Easy**

- [x] 系统配色优化（主要是左侧导航菜单）
- [ ] 头像右侧显示用户名，以及优化一下对应的下拉框 UI
- [ ] 首页开发（新增一些漂亮的图表）
- [x] 404、403 页面优化
- [ ] 权限管理页面布局优化
- [x] 登录页布局优化
- [x] 新增表格 CRUD 页面
- [ ] 新增一些常见功能示例（文件下载、打印、水印等）
- [ ] 新增 src/config/layout 配置项缓存功能
- [x] 路由的 icon 配置项支持 Element Plus 的 Icon
- [ ] 完善中文文档
- [ ] 新增英文文档
- [x] 新增英文 README
- [x] 新 Logo 设计
- [ ] keep alive 缓存
- [ ] 消息通知功能

**Medium**

- [ ] 新增大屏可视化页面
- [ ] 新增后端返回动态路由功能
- [ ] 新增不同的 layout 一键切换
- [ ] 新增菜单搜索功能

**Hard**

- [x]  暂无

**Comment by GreatWriter** [comment]
建议添加右上角的消息、待办信息等提示

**Comment by pany-ang** [comment]
> 建议添加右上角的消息、待办信息等提示，后台管理一般都离不开内容消息通知

可以，我加进待办列表

**Comment by 1229984599** [comment]
加油呀，每天上github第一时间就是看你得进度条，另外可以把Crud优先度提高吗?毕竟后台系统用得最多的就是Crud

**Comment by pany-ang** [comment]
> 加油呀，每天上github第一时间就是看你得进度条，另外可以把Crud优先度提高吗?毕竟后台系统用得最多的就是Crud

CRUD 太业务了，所以优先级并不高。但是你都这么说了，可以给你提高一下下

**Comment by 1229984599** [comment]
> > 加油呀，每天上github第一时间就是看你得进度条，另外可以把Crud优先度提高吗?毕竟后台系统用得最多的就是Crud
> 
> CRUD 太业务了，所以优先级并不高。但是你都这么说了，可以给你提高一下下

哈哈哈，那感情好，谢谢大佬啦，我当时也试着用vxe-table再封装了一下，但是封装得有点辣鸡

**Comment by pany-ang** [comment]
> > > 加油呀，每天上github第一时间就是看你得进度条，另外可以把Crud优先度提高吗?毕竟后台系统用得最多的就是Crud
> > 
> > 
> > CRUD 太业务了，所以优先级并不高。但是你都这么说了，可以给你提高一下下
> 
> 哈哈哈，那感情好，谢谢大佬啦，我当时也试着用vxe-table再封装了一下，但是封装得有点辣鸡

**Comment by pany-ang** [comment]
> > > > 加油呀，每天上github第一时间就是看你得进度条，另外可以把Crud优先度提高吗?毕竟后台系统用得最多的就是Crud
> > > 
> > > 
> > > CRUD 太业务了，所以优先级并不高。但是你都这么说了，可以给你提高一下下
> > 
> > 
> > 哈哈哈，那感情好，谢谢大佬啦，我当时也试着用vxe-table再封装了一下，但是封装得有点辣鸡

CRUD 写好了，你可以去瞅瞅

**Comment by 1229984599** [comment]
感谢感谢，我一直关注着的，哈哈哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 下午3:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [un-pany/v3-admin-vite] 维护计划 (Issue #12)





     
加油呀，每天上github第一时间就是看你得进度条，另外可以把Crud优先度提高吗?毕竟后台系统用得最多的就是Crud
  
CRUD 太业务了，所以优先级并不高。但是你都这么说了，可以给你提高一下下
  
哈哈哈，那感情好，谢谢大佬啦，我当时也试着用vxe-table再封装了一下，但是封装得有点辣鸡
   
CRUD 写好了，你可以去瞅瞅

**Comment by pany-ang** [comment]
消息通知也写好了，可以去瞅瞅是不是这样的 @GreatWriter

**Comment by yangzai316** [comment]
可以总是重定向到登录页，登录始终不成功，没法预览啊

**Comment by pany-ang** [comment]
> 可以总是重定向到登录页，登录始终不成功，没法预览啊

没法复现，能正常预览啊

**Comment by pany-ang** [comment]
> 建议添加搜索菜单，菜单多的时候非常实用！
> 
> [案例](https://xiaoxian521.github.io/vue-pure-admin)
> 
> ![图片](https://user-images.githubusercontent.com/28520524/210779742-f27e3e92-1d1e-4a9c-a276-71f136f3dc91.png)

这个功能一直在计划列表里有，抽空会做的

**Comment by yymjku18** [comment]
建议添加国际化切换

**Comment by pany-ang** [comment]
> 建议添加国际化切换

以前有，被我移除了。感觉用到的人不多

**Comment by pany-ang** [comment]
> 建议添加搜索菜单，菜单多的时候很实用！
> 
> [案例](https://xiaoxian521.github.io/vue-pure-admin)
> 
> ![图像](https://user-images.githubusercontent.com/28520524/210779742-f27e3e92-1d1e-4a9c-a276-71f136f3dc91.png)

菜单搜索已上线

**Comment by Gzbox** [comment]
这个项目真的是太棒了，作为新项目的基本框架，进行二次开发。作者辛苦了。 👍👍👍👍

**Comment by pany-ang** [comment]
> 这个项目真的是太棒了，作为新项目的基本框架，进行二次开发。作者辛苦了。 👍👍👍👍

感谢支持

**Comment by Agony95z** [comment]
大佬可以集成tailwind吗 写样式太累人了

**Comment by pany-ang** [comment]
> 大佬可以集成tailwind吗 写样式太累人了

已经集成了 unocss，其他的你可以自行集成哦

**Comment by mykite** [comment]
大佬后端返回权限渲染菜单的有在做了吗，这种一般增对权限的checkPermission  应该是具体到功能的

**Comment by pany-ang** [comment]
> 大佬后端返回权限渲染菜单的有在做了吗，这种一般增对权限的checkPermission 应该是具体到功能的

持续关注吧，最近有其他事耽搁了

**Comment by dootexto** [comment]
为什么constants/cache-key.ts会先于main.ts执行呢？实在搞不懂为什么

**Comment by offline24h** [comment]
api\hook-demo\use-fetch-select.ts中

const SELECT_RESPONSE_DATA = {
...
}
建议加个类型约束：
const SELECT_RESPONSE_DATA: ApiData = {
...
}

现在use-fetch-select.ts中的“disabled”字段与hooks\useFetchSelect.ts中的“disable”不一致了

**Comment by pany-ang** [comment]
> 为什么constants/cache-key.ts会先于main.ts执行呢？实在搞不懂为什么

因为 main.ts 中 import 导入的文件里用到了 constants/cache-key.ts

**Comment by pany-ang** [comment]
> > > 建议添加国际化切换
> > 
> > 
> > 以前有，被我移除了。感觉用到的人不多
> 
> 建议拉个分支出来来支持国际化，毕竟现在很多系统都需要的，这应该是个加分项，没有这个基本功能可能前期评估的时候就会把这个模板排除掉了。 感谢无私奉献，新年快乐。

后面看时间吧，最近比较忙

**Comment by pany-ang** [comment]
> api\hook-demo\use-fetch-select.ts中
> 
> const SELECT_RESPONSE_DATA = { ... } 建议加个类型约束： const SELECT_RESPONSE_DATA: ApiData = { ... }
> 
> 现在use-fetch-select.ts中的“disabled”字段与hooks\useFetchSelect.ts中的“disable”不一致了

可以自己加一下

**Comment by mcitem** [comment]
建议让app-loading能够适配暗色主题（即跟随设备默认设置，而不是只能白屏）

**Comment by pany-ang** [comment]
> 建议让app-loading能够适配暗色主题（即跟随设备默认设置，而不是只能白屏）

可以，我抽空看看

**Comment by wanzhe10** [comment]
希望作者大大，更新，后台返回路由表功能，万分感谢，@pany 是我吖！！@中不溜哈

**Comment by pany-ang** [comment]
> 希望作者大大，更新，后台返回路由表功能，万分感谢，@pany 是我吖！！@中不溜哈

开源都是为爱发电，今年在这个项目上的投入比较少，以 BUG 修复为和更新依赖配置为主。新功能可能得再等等

**Comment by csg2008** [comment]
> > 希望作者大大，更新，后台返回路由表功能，万分感谢，@pany 是我吖！！@中不溜哈
> 
> 开源都是为爱发电，今年在这个项目上的投入比较少，以 BUG 修复为和更新依赖配置为主。新功能可能得再等等

后台返回路由已开发好，请见PR

**Comment by csg2008** [comment]
> > > > 建议添加国际化切换
> > > 
> > > 
> > > 以前有，被我移除了。感觉用到的人不多
> > 
> > 
> > 建议拉个分支出来来支持国际化，毕竟现在很多系统都需要的，这应该是个加分项，没有这个基本功能可能前期评估的时候就会把这个模板排除掉了。 感谢无私奉献，新年快乐。
> 
> 后面看时间吧，最近比较忙

个人觉得可以把国际化加上，类似动态路由那样，只做一个实例页面就可以，不用抽专门的分支更方便。

**Comment by NicCraver** [comment]
@csg2008 厉害 膜拜 👍

**Comment by wanzhe10** [comment]
> 个人觉得当前基于角色的权限不太灵活，还容易跟后台角色绑定且粒度不好把控，优化一下怎么样？
> 
> 优化建议： 1、动态菜单是后台返回的，默认就是授权给用户可以访问菜单列表，不做权限检查 2、扩充菜单添加下级按钮资源，就是在页面的 children 中添加按钮级资源，页面中的按钮权限就与这个按钮资源绑定
> 
> 实例：动态路由页面 DirectivePermission 下新增个名为 add 的创建按钮，在页面中这个按钮就用 v-permission="['DirectivePermission:add']" 这个指令实现权限判断
> 
> 如果觉得可以，我继续把这个开发出来提交PR

感谢大神

**Comment by csg2008** [comment]
> 个人觉得当前基于角色的权限不太灵活，还容易跟后台角色绑定且粒度不好把控，优化一下怎么样？
> 
> 优化建议： 1、动态菜单是后台返回的，默认就是授权给用户可以访问菜单列表，不做权限检查 2、扩充菜单添加下级按钮资源，就是在页面的 children 中添加按钮级资源，页面中的按钮权限就与这个按钮资源绑定
> 
> 实例：动态路由页面 DirectivePermission 下新增个名为 add 的创建按钮，在页面中这个按钮就用 v-permission="['DirectivePermission:add']" 这个指令实现权限判断
> 
> 如果觉得可以，我继续把这个开发出来提交PR

已经将基于动态菜单的权限指令开发好了
