### ISSUE TITLE
install报错

### ISSUE THREAD

**Issue by lc5562010** [un-pany/v3-admin-vite#130]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/helper-create-class-features-plugin@^7.22.15.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liuchong/.npm/_logs/2023-09-05T02_21_59_338Z-debug-0.log

**Comment by pany-ang** [comment]
确保你的 node/pnpm 等版本和文档中提到的一致
