### ISSUE TITLE
Why store Token in Cookie and send it in Authorization Bearer Header?

### ISSUE THREAD

**Issue by pasestars** [un-pany/v3-admin-vite#137]
Why store Tooken in Cookie, after that send token over Authorization Bearer Header?
It sends duplicate Token in Header: Authorization and Cookie when the domain of FE and BE is the same.
![image](https://github.com/un-pany/v3-admin-vite/assets/53326132/91ebea30-9dbf-441b-9c19-854656e0c3c7)

**Comment by pany-ang** [comment]
Yes, this is done just to be compatible with both ways, just a defensive programming
