### ISSUE TITLE
fastmock 接口挂了

### ISSUE THREAD

**Issue by 593496637** [un-pany/v3-admin-vite#139]
![image](https://github.com/un-pany/v3-admin-vite/assets/15769004/a3294efc-edae-4fa5-97f6-43a19d510dbc)

**Comment by pany-ang** [comment]
现在应该没问题了

**Comment by 593496637** [comment]
挂梯子后不受影响，没有梯子的话还是不行

**Comment by pany-ang** [comment]
和你的网络环境有关，我这边的话倒是有无梯子都可以
