### ISSUE TITLE
代码高亮问题

### ISSUE THREAD

**Issue by lcc1121** [un-pany/v3-admin-vite#144]
小白一枚，看到大佬的代码非常感兴趣，但有个问题请问一下，为什么在这个项目里elemenui的代码也都会高亮，这与自己的组件有时候会混淆，是这个项目的配置问题吗

**Comment by pany-ang** [comment]
没太明白你的意思。组件不就应该高亮吗

**Comment by lcc1121** [comment]
之前自己写的组件才会高亮，用elementui组件应该不会高亮，例如我自己封装了一个my-button是会高亮的，但是我用el-button应该不会高亮，但是在大佬你这边的项目里el-button也会高亮。

**Comment by pany-ang** [comment]
高亮才是正常的
