### ISSUE TITLE
软件架构单一职责优化建议

### ISSUE THREAD

**Issue by jerry765** [un-pany/v3-admin-vite#145]
在项目架构层面，我发现存在一些模块违反了单一职责原则，这可能导致模块的复杂性增加，难以维护和扩展。以下是一些潜在的优化点：

- `/store/modules/user.ts`文件处理用户登录、获取用户信息、角色设置等多个职责。建议将用户认证（如登录）和用户信息管理（如获取用户信息、角色设置）分离成两个独立的模块。
- `/hooks/useFetchSelect.ts`自定义钩子包含了两个相关度不高的逻辑。建议将这些钩子拆分为更细粒度的钩子，每个钩子专注于单一功能。

我计划基于这些观点对项目进行针对性的优化，以提高代码的可读性和可维护性。如有不妥之处，还请不吝赐教。

**Comment by pany-ang** [comment]
我最近有事耽搁，后面我会仔细查看你的所有 PR，非常感谢你的建议！
