### ISSUE TITLE
页面切换内容不显示

### ISSUE THREAD

**Issue by ChenErik** [un-pany/v3-admin-vite#147]
这是bug的gif效果
![1](https://github.com/un-pany/v3-admin-vite/assets/37365363/b5cc7e1b-9937-45ab-a80a-07c3a09af1a9)
以下是我改动的代码
![1](https://github.com/un-pany/v3-admin-vite/assets/37365363/a509c50d-caea-4e60-bb3f-7ef0e22e6a34)

但是我如果把AppMain.vue中transition的mode去掉就没问题了

**Comment by pany-ang** [comment]
文档里有写，组件要保证一个根元素节点

**Comment by ChenErik** [comment]
我刚刚也发现了，注释也不能有☹️ ，感谢回复
