### ISSUE TITLE
软件架构错误处理优化建议

### ISSUE THREAD

**Issue by jerry765** [un-pany/v3-admin-vite#148]
在项目架构方面，我注意到多个模块在处理错误时缺乏统一一致。为了提高代码健壮性，我建议引入一个统一的错误处理机制，以下为主要的改动点：

1. 统一错误类型：定义 `Api Error` 和 `Common Error`
2. 统一错误处理函数：创建错误处理函数，捕获和处理所有相关错误，并考虑提供适当的用户反馈
3. 更新相关文件：在原有的逻辑中引入错误处理函数
 
通过这些改动，希望提高应用的整体稳定性，并在出现错误时提供更清晰的用户反馈。这些优化将有助于提升用户体验，并使代码更易于维护和扩展。

**Comment by pany-ang** [comment]
我最近有事耽搁，后面我会仔细查看你的所有 PR，非常感谢你的建议！

**Comment by pany-ang** [comment]
非常感谢，但很遗憾该 PR 不适合本项目
