### ISSUE TITLE
求助：希望 navbar 的折叠能根据 导航的最大宽度 最小限度的去折叠，该怎么修改代码来实现呢？

### ISSUE THREAD

**Issue by Gzbox** [un-pany/v3-admin-vite#152]
<img width="1563" alt="image" src="https://github.com/un-pany/v3-admin-vite/assets/21010051/c9460a56-36d1-4213-9dfe-4fd0b253d6a3">

实际他的宽度还很富裕 完全不需要折叠那么多呢  请大佬指点   @pany-ang

**Comment by pany-ang** [comment]
你可以研究一下 NavigationBar -> Sidebar -> el-menu 这三个组件，你描述的问题应该是和 el-menu 的自适应宽度有关，可能有其他 css 属性影响了 el-menu 对宽度的判断

**Comment by Gzbox** [comment]
感谢，已找到原因，我尝试修复了一下，提个 PR  您审核一下

#153
