### ISSUE TITLE
内容区全屏 下拉框内容,弹窗内容无法显示

### ISSUE THREAD

**Issue by Florist-xu** [un-pany/v3-admin-vite#154]
![image](https://github.com/un-pany/v3-admin-vite/assets/107057628/9c3d7f07-591a-43d6-a897-1209c077f5ea)
![image](https://github.com/un-pany/v3-admin-vite/assets/107057628/de205ab4-6275-49f1-be9f-0b1b766f70c4)

**Comment by pany-ang** [comment]
优先使用提供的另外一个全屏功能，这个功能意义不大了

**Comment by pany-ang** [comment]
952b327261c83b799104f5a31cba8124061aafe1 这个 commit 比较优雅的解决了这个问题
