### ISSUE TITLE
能不能把登录模块给去掉

### ISSUE THREAD

**Issue by rdyan0053** [un-pany/v3-admin-vite#159]
只需要给公司指定人员使用，不需要登陆模块，如何去除？

**Comment by pany-ang** [comment]
当然可以...删除掉相关代码即可。然后记得修改一下路由守卫的逻辑，没有登陆模块的话，基本上就是直接放行了

**Comment by rdyan0053** [comment]
好的，感谢

**Comment by rdyan0053** [comment]
感觉这个模板很好，但是对我来说还是太复杂了，我只想弄个简单的，然后写写前端请求，我主要是弄后端😭
