### ISSUE TITLE
怎么感觉meta.hidden不能用？是我使用方法有问题？

### ISSUE THREAD

**Issue by w569638598** [un-pany/v3-admin-vite#160]
![微信截图_20240112174924](https://github.com/un-pany/v3-admin-vite/assets/30279222/e39adc35-53f1-4fcc-80af-1e7559dc1b9f)
![微信截图_20240112175035](https://github.com/un-pany/v3-admin-vite/assets/30279222/baa18edb-fa5b-48ab-900e-20e3e14322ec)

**Comment by pany-ang** [comment]
能在开源项目最新的代码上复现吗？告诉我一下复现代码

**Comment by w569638598** [comment]
没事，我用法有问题，看了下代码，你只在路由顶级判断hidden属性了，我这个页面路由写在子路由里面了。

**Comment by kagg886** [comment]
玩原神玩的

**Comment by pany-ang** [comment]
@w569638598 我修复了一个可能和你提到的问题有关的 BUG，你可以同步更新一下代码：b2597f1ffd9f7a6595988e3a587f30025a581641
