### ISSUE TITLE
开启全屏后顶部存在一个margin

### ISSUE THREAD

**Issue by Stonmore** [un-pany/v3-admin-vite#165]

**Comment by Aaron-zon** [comment]
![image](https://github.com/un-pany/v3-admin-vite/assets/47178158/9484d6ef-e507-4845-8a80-2f26134746a0)
木有发现，给张图呗

**Comment by Stonmore** [comment]
抱歉，是内容区全屏
![Uploading Snipaste_2024-02-23_17-09-41.png…]()

**Comment by Stonmore** [comment]
<img width="1512" alt="Snipaste_2024-02-23_17-09-41" src="https://github.com/un-pany/v3-admin-vite/assets/38468269/fb617752-c5bb-4bb6-a3b4-df843f5a5627">

**Comment by Stonmore** [comment]
看了源码应该是顶部菜单没有隐藏 document.query('html')这块出了问题

**Comment by Aaron-zon** [comment]
这里嘛，是个padding吧
![image](https://github.com/un-pany/v3-admin-vite/assets/47178158/e233fe68-4096-43f4-9296-c31f0c9e5c60)

**Comment by Stonmore** [comment]
对的是这块，全屏的时候上方有个div没有隐藏

**Comment by pany-ang** [comment]
我很早就注意到了这个问题，所以开发了 “内容区放大” 来代替 “内容区全屏”
