### ISSUE TITLE
 iPhone 手机用浏览器访问本地开发环境在登录成功之后白屏

### ISSUE THREAD

**Issue by xdlgj** [un-pany/v3-admin-vite#181]
通过npm run dev 系统项目之后，使用电脑端访问正常，但是使用手机浏览器登录之后是空白，这是为什么呢?

**Comment by xdlgj** [comment]
iPhone12, iPhone 14 pro max，safari浏览器和chrome浏览器都不行：
![Uploading aaa.jpg…]()

**Comment by xdlgj** [comment]
报错信息：
WARNING [Vue warn]: Unhandled error during execution of watcher callback
at <Index key=1 class="right-menu-item">
at <Index>
at <LeftMode key=0 >
at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref<>>
at <RouterView>
at <ElConfigProvider locale= [object Object] >
at <App>
![b](https://github.com/un-pany/v3-admin-vite/assets/42741025/b3b04eba-38ba-48d8-8fd1-d00ceeca44dd)

**Comment by pany-ang** [comment]
我会花时间排查一下这个问题

**Comment by pany-ang** [comment]
#183 已修复
