### ISSUE TITLE
这个页面好多黄色波浪线警告

### ISSUE THREAD

**Issue by cscsb** [un-pany/v3-admin-vite#184]
![20240411182954](https://github.com/un-pany/v3-admin-vite/assets/49179157/cd111caf-ac18-4576-9b9c-c08392cf6556)

**Comment by Aaron-zon** [comment]
![image](https://github.com/un-pany/v3-admin-vite/assets/47178158/2e87426f-0f0b-47c6-a86a-dad603f2ce21)
可能是编辑器配置或插件的问题
