### ISSUE TITLE
为什么模块和组件都正常的引入也可以使用，但编辑器一直报找不到模块呢

### ISSUE THREAD

**Issue by hykBigHeart** [un-pany/v3-admin-vite#186]
![问题图片](https://github.com/un-pany/v3-admin-vite/assets/83852132/2107c252-8536-48c5-8fc4-05369e6a91d4)
请教一下大佬，为什么模块和组件都正常的引入也可以使用，但编辑器一直报找不到模块呢

**Comment by Aaron-zon** [comment]
安装Vue - Official插件
![image](https://github.com/un-pany/v3-admin-vite/assets/47178158/7b48151d-351b-4ae4-8ecb-e76db0ed814c)
