### ISSUE TITLE
我保存后自动格式化代码的设置失效了

### ISSUE THREAD

**Issue by guoyianlin** [un-pany/v3-admin-vite#192]
在这个项目里修改代码保存后 不会自动格式化代码了，我自己是有配置这个选项，想问下项目里哪个 配置影响了【保存自动格式化】的功能

**Comment by pany-ang** [comment]
`.vscode/settings.json` 目录下有相关配置，并且已经配置好了自动格式化。可以自行排查一下。

**Comment by JuckZ** [comment]
需要在settings.json中增加一行配置
"prettier.enable": true

**Comment by JuckZ** [comment]
我试过了，现在直接拉取新代码什么都不改动，也是无法自动格式化的，需要增加一个配置
我提交了一个PR https://github.com/un-pany/v3-admin-vite/pull/195

**Comment by pany-ang** [comment]
检查一下 eslint 版本是否和仓库保持一致，目前是 8.57.0
