### ISSUE TITLE
表格数据类型的名称问题

### ISSUE THREAD

**Issue by LeiYangGH** [un-pany/v3-admin-vite#196]
GetTableRequestData GetTableData GetTableResponseData可不可以把Get去掉，或改其他更有业务逻辑含义的名称。比如Person, Employee, Student之类。
何况还有函数名为getTableData，初看有点晕啊。

**Comment by pany-ang** [comment]
如果你想到更好的命名，欢迎 PR 或者留言~

**Comment by LeiYangGH** [comment]
至少把Get去掉。我上面已经建议了啊。

**Comment by NicCraver** [comment]
已PR #197
