### ISSUE TITLE
ignore pnpm-lock.yaml

### ISSUE THREAD

**Issue by LeiYangGH** [un-pany/v3-admin-vite#202]
pnpm i后多了这个文件，希望忽略。

**Comment by pany-ang** [comment]
自行选择忽略即可。通常情况下，这个文件存在更好

**Comment by LeiYangGH** [comment]
我觉得不太方便的是，如果我希望经常pull你的最新更新，又不想有自己的commits，自己本地运行又一定会有lock文件的diff。
