### ISSUE TITLE
请教/讨论：关于cookie的存取

### ISSUE THREAD

**Issue by LeiYangGH** [un-pany/v3-admin-vite#203]
网上大多数的教程关于登录和cookie的步骤是这样的：服务端在登录成功的响应头中添加 Set-Cookie字段，
浏览器自动保存cookie并在后续请求中自动带上此cookie。

而你的代码里似乎是前端js用setToken(data.token)主动加了个值为响应body里的属性的cookie，并在后续request中取出cookie并组装Authorization: Bearer ${token}。
相比之下显得更冗长，而且数据存储在别的地方应该是一样的效果，比如LocalStorage，没用到cookie的特色功能。
请问为什么摒弃浏览器对“cookie”的自动处理？

**Comment by pany-ang** [comment]
因为你描述的是传统的 cookie 鉴权模式，而我们这里用的是 token 鉴权模式。只是为了兜底才将 token 放置一份在了 cookie 里
