### ISSUE TITLE
侧边栏切换按钮下面的尖角图标是作什么的？

### ISSUE THREAD

**Issue by LeiYangGH** [un-pany/v3-admin-vite#204]
![image](https://github.com/user-attachments/assets/4ab571ea-d6da-4f88-b906-9702ef88e3df)
如图，在各种模式下都没找到点击对应的效果。
在代码里面是哪个位置添加的？

**Comment by NicCraver** [comment]
src/layouts/components/TagsView/ScrollPane.vue
控制左右滚动的，菜单多了就会触发左右滚动
