### ISSUE TITLE
当浏览器窗口缩放至一定宽度时，页面重载了

### ISSUE THREAD

**Issue by xqmm** [un-pany/v3-admin-vite#212]
当浏览器窗口缩放至一定宽度时，页面重载了

**Comment by pany-ang** [comment]
这是 layout 切换了导致的正常现象

**Comment by xqmm** [comment]
如果缩放的时候不想要当前页面重载，哪里可以禁止掉吗

**Comment by pany-ang** [comment]
可以自己按照自己的需求修改一下 `src/layouts/index.vue` 文件里的 `isMobile`
