### ISSUE TITLE
管理平台处在某个界面，电脑息屏较长时间，再去切换左侧菜单栏。控制台报错找不到相应模块，路由跳转失败

### ISSUE THREAD

**Issue by xqmm** [un-pany/v3-admin-vite#213]
管理平台处在某个界面，电脑息屏较长时间，再去切换左侧菜单栏。控制台报错找不到相应模块，路由跳转失败,但是强制刷新页面就正常了
 
vue-D7f11OzQ.js:29 TypeError: Failed to fetch dynamically imported module: https://xxxxxxxxxxxxxxxxxxxxxxxxx/static/index-D62-2owO.js;
index-DZH05Rmz.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
index-DFNzhxyN.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by pany-ang** [comment]
可以检查一下是不是息屏期间服务器上的前端静态资源被更新了

**Comment by xqmm** [comment]
你很棒啊
