### ISSUE TITLE
关于element表格的示例

### ISSUE THREAD

**Issue by MelodyLLL** [un-pany/v3-admin-vite#216]
查看了demo网址发现，搜索表格的时候分页展示有问题，搜索出来的唯一值但是页码展示了十条。

**Comment by MelodyLLL** [comment]
查看代码发现，搜索似乎并没有重置回第一页

**Comment by pany-ang** [comment]
接口返回的 total 字段导致的错误，我调整一下接口响应数据

**Comment by pany-ang** [comment]
接口已更新

**Comment by MelodyLLL** [comment]
> 接口已更新

搜索时的页码还是有点问题，虽然搜索后请求发出了第一页，但是页码组件还是留在了上次页码。demo搜索不出多页的数据情况，可以造点数试下

**Comment by MelodyLLL** [comment]
> > 接口已更新
> 
> 搜索时的页码还是有点问题，虽然搜索后请求发出了第一页，但是页码组件还是留在了上次页码。demo搜索不出多页的数据情况，可以造点数试下

忽略上面，未拉最新代码。刚pull发现currentPage的属性已经改过了。
