### ISSUE TITLE
侧边栏高度自适应问题

### ISSUE THREAD

**Issue by youzi7** [un-pany/v3-admin-vite#217]
在笔记本上试了下demo，当屏幕较小时，侧边展开后最下面菜单栏未显示部分被剪掉了，再往下拉也没有了，在哪里调整能解决，谢谢

<img width="405" alt="image" src="https://github.com/user-attachments/assets/163ca8ad-9ddd-40d5-9ffb-f29baaf13023">

**Comment by pany-ang** [comment]
该问题已在 4.x 分支解决，具体 commit 如下：https://github.com/un-pany/v3-admin-vite/commit/5b452a450e087647eafeb2d0e586b659759d9334

并且发行在 4.5.5 版本中：https://github.com/un-pany/v3-admin-vite/releases/tag/v4.5.5

**Comment by pany-ang** [comment]
4.5.5 版本引起了一个小 bug，已在 4.5.6 版本修复：https://github.com/un-pany/v3-admin-vite/releases/tag/v4.5.6

**Comment by youzi7** [comment]
online preview 更新了吗？还是没有解决啊，我自己更改了问题也没解决
![image](https://github.com/user-attachments/assets/4db388cc-e25b-4dd3-8707-64b052b60b64)

**Comment by pany-ang** [comment]
已解决，见发行版 v4.5.6。主分支和预览链接正在迭代 v5.0 功能
