### ISSUE TITLE
跨域

### ISSUE THREAD

**Issue by wjj-phoenix** [un-pany/v3-admin-vite#218]
代理配置截图
![image](https://github.com/user-attachments/assets/a8e87c93-1de4-40b9-9d92-9c49fe1ebd1d)
接口请求截图
![image](https://github.com/user-attachments/assets/7aba6b66-7d72-4161-89fa-8a2cc5695aa6)
出现的错误截图
![image](https://github.com/user-attachments/assets/71e1b752-caa5-4234-a8af-aa3d6b80d2f1)
swagger请求后端接口
![image](https://github.com/user-attachments/assets/a31a743f-acb9-4dab-a82b-3827e7841de5)

问题描述：
我在项目中使用了代理配置，并开启了跨域的设置，但是前端在请求后端接口时还是出现了跨域的问题，单独在Swagger中请求后端接口是能够成功请求到的

**Comment by pany-ang** [comment]
有教程：https://juejin.cn/post/7209852595002409018
