### ISSUE TITLE
你好当前主分支，在选择顶部模式时每个菜单的第一次选择都会报着错误，请问如何修改

### ISSUE THREAD

**Issue by CodeWizardX11** [un-pany/v3-admin-vite#224]
![image](https://github.com/user-attachments/assets/515b0abf-c8c5-4af5-8519-2f56cf4e2051)
你好当前主分支，在选择顶部模式时每个菜单的第一次选择都会报着错误，请问如何修改

**Comment by pany-ang** [comment]
这是新版浏览器的无障碍规则，是 element plus 的元素引起的，可以等待后续它的更新，现在无视即可

**Comment by CodeWizardX11** [comment]
好的，谢谢
