### ISSUE TITLE
[bug report] router switch error

### ISSUE THREAD

**Issue by vkm0303** [un-pany/v3-admin-vite#27]
**When the component has mutiple root, the <Transition/> component can't be animated that target compontent can't be displayed(blank content).**

![image](https://user-images.githubusercontent.com/64176534/200467385-0e00e898-e3f8-49f5-b872-97b83f269745.png)
![image](https://user-images.githubusercontent.com/64176534/200467401-27f07f54-c0ee-44a8-8129-d91c7f420e1f.png)

**Comment by pany-ang** [comment]
https://github.com/un-pany/v3-admin/pull/9

**Comment by pany-ang** [comment]
所以这个问题我注意到很久了，暂时是没办法解决的，只能要求用户自己写页面的时候，像 vue2 一样包裹一个根元素
