### ISSUE TITLE
跳转页面时候 No match found for location with path 无法跳转

### ISSUE THREAD

**Issue by lq0910** [un-pany/v3-admin-vite#3]
vue-router.esm-bundler.js:72 
        
       [Vue Router warn]: No match found for location with path "/paiming/paiminglist"

**Comment by lq0910** [comment]
@pany-ang

**Comment by pany-ang** [comment]
只是开发环境的控制台警告吗？还是说真的无法跳转到对应路由？

**Comment by lq0910** [comment]
已收到。我会马上查看。

**Comment by lq0910** [comment]
@pany-ang  不只是警告、是无法跳转到指定路由、使用vue router.push跳转会出现这个问题，刷新后又可以了

**Comment by pany-ang** [comment]
我没法复现，你应该检查一下你的代码，这应该是和这个项目没关系。或者你可以加群截个图看看
