### ISSUE TITLE
页面keep-alive缓存后，关闭页面在打开还是旧的，另外右键刷新路径拼接不对，刷新也是无效的【bug】

### ISSUE THREAD

**Issue by wangkris03** [un-pany/v3-admin-vite#36]

**Comment by pany-ang** [comment]
有示例吗？视频 & GIF 都行。不过看你描述的话，开启缓存后，页面是旧页面，这个不就是开启缓存之后应该有的效果吗

**Comment by chenchaoc** [comment]
> 有示例吗？视频 & GIF 都行。不过看你描述的话，开启缓存后，页面是旧页面，这个不就是开启缓存之后应该有的效果吗

他的意思是在tagView关闭掉组件后，缓存的组件应该销毁，然后再打开应该是1个新的

**Comment by pany-ang** [comment]
> > 有示例吗？视频 & GIF 都行。不过看你描述的话，开启缓存后，页面是旧页面，这个不就是开启缓存之后应该有的效果吗
> 
> 他的意思是在tagView关闭掉组件后，缓存的组件应该销毁，然后再打开应该是1个新的
> 
> 以前是[vue-element-admin](https://github.com/PanJiaChen/vue-element-admin/blob/master/src/layout/components/TagsView/index.vue)做了keep-alive处理的，你这边已经删除掉了

了解了，这个还是毕竟简单的，自己加一下就行。我也在代码里预留了对应的位置。

**Comment by pany-ang** [comment]
keep alive 功能已经上线 @wangkris03 @chenchaoc
