### ISSUE TITLE
【配套API】可以看看这个项目的配套API嘛？

### ISSUE THREAD

**Issue by Chenchengnian** [un-pany/v3-admin-vite#37]

**Comment by pany-ang** [comment]
是 easy-mock 来模拟的真实接口，并没有实际的后端代码

**Comment by YL1217** [comment]
> 是 easy-mock 来模拟的真实接口，并没有实际的后端代码

你好，我最近在学eggjs，不知道楼主有没有兴趣开发配套的node项目

**Comment by pany-ang** [comment]
> > 是easy-mock来模拟的真实接口，并没有实际的后端代码
> 
> 你好，我最近在学eggjs，不知道楼主有没有兴趣开发套装的节点项目

没什么时间写。你可以自己写一个配套的后端并开源，合适的话，我会在项目里放上你的 GitHub 地址

**Comment by Chenchengnian** [comment]
> 

好的,那我flask起个服务,直接按照mock接口的返回值去构建结构体就行了吧?

不知道有没有接口文档之类的,毕竟前端是直接套用大哥的,后端自己写联调起来有难度

**Comment by pany-ang** [comment]
登录模块一共三个接口，表格模块 CRUD 一共四个接口。直接看控制台就行了 @Chenchengnian

**Comment by pany-ang** [comment]
我整理成教程了：https://juejin.cn/post/7249382407244087351
