### ISSUE TITLE
CORS 切换为反向代理一直报cors error

### ISSUE THREAD

**Issue by 13kay** [un-pany/v3-admin-vite#4]
在vit.config.ts中开启反向代理之后还是一直报cors error，是遗漏了其他某个配置吗？

**Comment by pany-ang** [comment]
多半是配错了，导致没有代理成功

**Comment by pany-ang** [comment]
可以检查一下 .env 配置

**Comment by 13kay** [comment]
文档可以提一下这个同步配置
后端配置CORS麻烦的时候反向代理比较方便
