### ISSUE TITLE
开发阶段保存是，热更新问题

### ISSUE THREAD

**Issue by wangkris03** [un-pany/v3-admin-vite#45]
![截图20232214300](https://user-images.githubusercontent.com/51576583/216248900-dda0dd52-454c-46f2-a9fb-387c02b934c6.png)

**Comment by pany-ang** [comment]
建议检查一下路由、页面、组件等的 Name 是否唯一，大小写是否正确；路由 Name 和组件名是否一致

**Comment by wangkris03** [comment]
> 建议检查一下路由、页面、组件等的 Name 是否唯一，大小写是否正确；路由 Name 和组件名是否一致

项目拉下来就会呢

**Comment by pany-ang** [comment]
我并不能复现你说的 “项目拉下来就会”，你确定你没有新增路由、页面，其他代码吗

**Comment by wangkris03** [comment]
> 我并不能复现你说的 “项目拉下来就会”，你确定你没有新增路由、页面，其他代码吗

开启了 keep-alive

**Comment by pany-ang** [comment]
那就说明大概率是你  keep-alive 相关的代码存在一定问题

**Comment by pany-ang** [comment]
你可以直接去网上搜索你的报错提示，可能会有一些解决办法

**Comment by pany-ang** [comment]
@wangkris03 keep alive 功能已经上线，你可以对比着看看
