### ISSUE TITLE
切换菜单，底部有横向滚动条

### ISSUE THREAD

**Issue by thousmile** [un-pany/v3-admin-vite#51]
左侧菜单  切换时，底部有横向滚动条

![QQ截图20230216145420](https://user-images.githubusercontent.com/28520524/219290622-970c98ab-5223-4bee-b6b7-6e6a69f7fadc.png)

**Comment by pany-ang** [comment]
1. 去代码里关闭或修改切换路由时的动画
2. 去设置里关闭 “固定 Header”

建议直接选 2
