### ISSUE TITLE
是否可以加个从后台动态获取菜单的功能呢

### ISSUE THREAD

**Issue by lizcao** [un-pany/v3-admin-vite#53]
很棒的项目！是否可以加个从后台动态获取菜单的功能呢，比如mock一个后台接口，返回菜单数据进行渲染？

**Comment by pany-ang** [comment]
后端返回动态路由这个功能在计划中

**Comment by lizcao** [comment]
有大概的时间节点吗

**Comment by pany-ang** [comment]
没有，抽空写。如果你感兴趣的话，欢迎 PR~

**Comment by Bill70058** [comment]
> 很棒的项目！是否可以加个从后台动态获取菜单的功能呢，比如mock一个后台接口，返回菜单数据进行渲染？

https://github.com/Bill70058/v3-admin-vite/tree/async-route
我写了个大概的，你的需求是这样吗，主要修改查看最新的一条commit

**Comment by chunfenghuayu1** [comment]
> > 很棒的项目！是否可以加个从后台动态获取菜单的功能呢，比如mock一个后台接口，返回菜单数据进行渲染？
> 
> https://github.com/Bill70058/v3-admin-vite/tree/async-route 我写了个大概的，你的需求是这样吗，主要修改查看最新的一条commit

那个import好像用不了啊🤔️。我在panjiachen魔改的模版上试过glob方法。页面刷新可以载入路由，只有切换三次以上侧边栏就会组建丢失，空白页面。

**Comment by pany-ang** [comment]
后端返回动态路由将在后续逐步推出，这个 issue 先关闭了
