### ISSUE TITLE
toggle tabs issue

### ISSUE THREAD

**Issue by gerryge** [un-pany/v3-admin-vite#54]
When the tabs more than the screen width, it cannot auto scoll to that tab after you click the menu which is hidden.

![tab toogle issue](https://user-images.githubusercontent.com/6952917/221485676-80cd52a8-d2c8-45d5-9d4b-0afe64286bd0.gif)

Should like this:
![image](https://user-images.githubusercontent.com/6952917/221485005-fc16d2f8-a5c7-41bb-958a-02e1cc39dbf1.png)

**Comment by pany-ang** [comment]
Thanks, I may take the time to optimize this experience, and you are welcome to contribute a PR directly
