### ISSUE TITLE
请问有没有刷新token的功能？

### ISSUE THREAD

**Issue by lianyitj** [un-pany/v3-admin-vite#55]
如题

**Comment by pany-ang** [comment]
没有，token 过期后会要求重新登录

**Comment by lianyitj** [comment]
哦，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月28日(周二) 上午9:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [un-pany/v3-admin-vite] 请问有没有刷新token的功能？ (Issue #55)




 
没有，token 过期后会要求重新登录
