### ISSUE TITLE
vue3的报错，打开控制台会出现奇怪断点

### ISSUE THREAD

**Issue by Bill70058** [un-pany/v3-admin-vite#58]
使用vue3的时候经常会出现一种情况，语法写法没问题，但是打开控制台就会出现奇怪断点，点击继续运行却没有报错
`
async function waitForDomElementReady() {
  try {
    return await waitFor(() => {
      let mainText = getMainText(document.body);
      if (mainText && mainText.length >= 10)
        return !0;
      throw new Error("there is no main text");
    }, { timeout: 1e4 }), !0;
  } catch (e3) {
    throw e3;
  }
}
`
在throw new Error("there is no main text");这行

**Comment by pany-ang** [comment]
你没有提供最小复现，我也没办法给你排查。不过 ，业务问题最好自己慢慢调试解决，我这边主要还是解决该项目框架的问题

**Comment by Bill70058** [comment]
> 你没有提供最小复现，我也没办法给你排查。不过 ，业务问题最好自己慢慢调试解决，我这边主要还是解决该项目框架的问题

不是业务上的，比如我注释掉了app.vue里的ElNotification这一块就回触发抛出异常，我做了个复现的简单[demo](https://github.com/Bill70058/vue3-demo)

**Comment by Bill70058** [comment]
> 你没有提供最小复现，我也没办法给你排查。不过 ，业务问题最好自己慢慢调试解决，我这边主要还是解决该项目框架的问题

找到问题了，是某个插件搞得鬼😂
