### ISSUE TITLE
Sidebar数据量较多时，滚动到最下方背景丢失

### ISSUE THREAD

**Issue by Li-Ger** [un-pany/v3-admin-vite#60]
![image](https://user-images.githubusercontent.com/57828100/224986458-24eec75a-5635-4978-b866-55a89c3a6726.png)
当sidebar的最后一个是一个没有二级的菜单时，滚动到最下方，背景就变成透明的了

**Comment by pany-ang** [comment]
好的，我会尽快修复

**Comment by pany-ang** [comment]
@QC2168 感谢

**Comment by pany-ang** [comment]
@Li-Ger 已修复
