### ISSUE TITLE
手机访问web会显示白屏

### ISSUE THREAD

**Issue by lishenli1994** [un-pany/v3-admin-vite#72]
![1](https://user-images.githubusercontent.com/16386064/231688124-175d7f91-bd13-445a-997d-d2746f813329.png)
![2](https://user-images.githubusercontent.com/16386064/231688151-151d1d2c-1da1-46e5-8de2-ecb54b3a6bbb.jpg)
如图，上面是PC的适配模式，下面是iphone访问safari的显示

**Comment by pany-ang** [comment]
好像不能复现，麻烦提供一下 iPhone 型号，iOS 版本，Safari 版本
