### ISSUE TITLE
tag管理按钮点击无反应

### ISSUE THREAD

**Issue by kcaco2000** [un-pany/v3-admin-vite#76]
tag管理按钮点击无反应，控制台也没有报错信息
![image](https://user-images.githubusercontent.com/42790380/234156017-bdc686ed-28f3-4c8f-b62f-2405917fa20d.png)

**Comment by pany-ang** [comment]
这是用来滚动标签的，你的截图上显示标签并没有超出可视区，所以无法滚动

**Comment by kcaco2000** [comment]
哦哦哦，抱歉，我还以为是标签管理，我关闭issue了。
