### ISSUE TITLE
Argument of type '{ class: string; }' is not assignable to parameter of type 'string & Record<string, unknown>'

### ISSUE THREAD

**Issue by unclemeric** [un-pany/v3-admin-vite#78]
请问执行build:prod报错如图，是怎么回事呢，dev运行没问题呢
![WX20230428-173402@2x](https://user-images.githubusercontent.com/6083914/235112313-54e192bd-cad9-4b7e-997b-f9b3e8b8fd3c.png)

**Comment by pany-ang** [comment]
升级 vue-tsc 到最新版

**Comment by pany-ang** [comment]
或者固定 vue-tsc 1.4.4

**Comment by unclemeric** [comment]
> 或者固定 vue-tsc 1.4.4

升级到最新版1.6.0不行，固定1.4.4版本就可以了。大佬666

**Comment by pany-ang** [comment]
最新版目前是 1.6.1
