### ISSUE TITLE
最新版 run 不起来 不知道为什么

### ISSUE THREAD

**Issue by xuergo** [un-pany/v3-admin-vite#8]
![image](https://user-images.githubusercontent.com/46159623/179510693-74ddc6e7-f208-4e78-836b-727458bbfd1a.png)

**Comment by xuergo** [comment]
pnpm i 了也没有报错

**Comment by pany-ang** [comment]
node 版本 16+
pnpm 版本 7.x
pnpm i
pnpm dev

**Comment by pany-ang** [comment]
删除 node_modules 和 .lock 文件后再次尝试
