### ISSUE TITLE
有没有一个基于js 和vite脚手架的项目,不用ts写的

### ISSUE THREAD

**Issue by Lollipope** [un-pany/v3-admin-vite#83]
RT.

**Comment by pany-ang** [comment]
没，日常业务开发使用 TS 也不难，花一个下午入门一下就好了：https://juejin.cn/post/6946391746628550669

**Comment by Lollipope** [comment]
@pany-ang 我明白,我只是不想写一些和业务无关的代码,特别是扩展字段和方法的时候,特别繁琐; 如果是写库的话可能就用ts了.但是具体项目用ts 还是感觉有些鸡肋.也不是说ts不好.纯个人感受

**Comment by pany-ang** [comment]
嗯嗯，但依旧推荐你用 TS，花点时间习惯了它的繁琐后，它是真的好用
