### ISSUE TITLE
三级路由keepAlive缓存问题

### ISSUE THREAD

**Issue by universon123456** [un-pany/v3-admin-vite#85]
您好：
非常感谢您这个非常棒的开源项目，本人在table部分keepAlive是成功的，但如果是三级及三级以上使用keepAlive确是失效的，麻烦有空看看？

**Comment by pany-ang** [comment]
官方似乎只能支持二级路由缓存。你可以等我后续的更新，或是你自己做一下路由数组的扁平化，来实现三级路由缓存

**Comment by universon123456** [comment]
好，谢谢

**Comment by pany-ang** [comment]
#93

**Comment by pany-ang** [comment]
#93 已实现并合并
