### ISSUE TITLE
去掉 .editorconfig 中的 end_of_line 设置

### ISSUE THREAD

**Issue by xiongdi94** [un-pany/v3-admin-vite#88]
.editorconfig 中的配置` end_of_line = lf ` 不适用于 windows，建议去掉。

**Comment by pany-ang** [comment]
配置为 lf 在 windows 上不会造成什么问题，同时还能兼容 linux 等系统

**Comment by xiongdi94** [comment]
一般 git 的 core.autocrlf 设置为 true，所以在 windows 上 checkout 之后都会是 crlf，用VSCode修改保存后又会变成 lf

**Comment by pany-ang** [comment]
这一块不是很熟悉，有文档参考吗

**Comment by xiongdi94** [comment]
git 设置相关的文档：[https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=windows](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=windows)

其他项目类似的问题：[https://github.com/frintjs/frint/pull/286](https://github.com/frintjs/frint/pull/286)

**Comment by pany-ang** [comment]
我大致看了一下，感觉依旧是配置为 end_of_line = lf 比较通用：

1. windows 上 的 git core.autocrlf 为 true 时，在 windows 上 checkout 之后会是 crlf，由于配置了 end_of_line = lf，修改保存后又会变成 lf，但是不论是 crlf 还是 lf，vscode 都能自动适应，所以此时不会产生任何问题。在 git 提交代码时，最终会以 lf 模式进行提交，此时也不会有任何问题。
2. 但是当 windows 上 的 git core.autocrlf 为 fasle 时，配置  end_of_line = lf 的好处似乎就突显出来了，因为这能尽可能的使提交到 GitHub 上的代码是 lf 模式，能兼容更多的操作系统。
3. 绝大多数情况下， end_of_line = lf 这个配置似乎都是可要可不要的状态，所以感觉没必要移除它。

不知道你还有没有其他建议给我这边参考？

**Comment by xiongdi94** [comment]
git提交不会有任何问题，但是在 windows 上修改保存然后撤销修改后，也会被 git diff 出来
```
$ git diff
warning: LF will be replaced by CRLF in src/store/modules/permission.ts.
The file will have its original line endings in your working directory
```
只有在执行 git add 之后才会消失

**Comment by pany-ang** [comment]
哦对，这个问题我是知道的，我一直选择容忍它。

**Comment by pany-ang** [comment]
但是如果删了 end_of_line = lf，真的不会造成更多问题吗？比如 git core.autocrlf 为 fasle 时

**Comment by xiongdi94** [comment]
是的，但好在 git 安装默认会选上的。如果有人的提交是 crlf ，一般也能在 review 时看出来。如果这个项目有很多新手使用，这个地方确实会造成一些迷惑。所以 whatever，看你怎么考虑了。

**Comment by pany-ang** [comment]
我可能会先保留这个配置，在我不是完全掌握这个配置的情况下。我只能参考更优秀的作者和开源项目。比如托尼的：https://github.com/antfu/vitesse/blob/main/.editorconfig

**Comment by pany-ang** [comment]
你可以加一下我的微信，我拉你进一下维护群
