### ISSUE TITLE
请问能把 easy-mock 里面的 mock json 开源一下吗

### ISSUE THREAD

**Issue by Hysian** [un-pany/v3-admin-vite#89]
想结合 mock json 的数据来调试学习

**Comment by pany-ang** [comment]
登录模块三个接口，表格模块一个接口，一共四个。先直接看控制台就行了，待会我发出来一下吧。

**Comment by pany-ang** [comment]
说错了，登录模块三个，表格模块四个，一共7个。header 校验实际上是校验的 token，这是后端的知识，你可以去搜一搜相关知识

**Comment by pany-ang** [comment]
我整理成教程了：https://juejin.cn/post/7249382407244087351
