### ISSUE TITLE
vue-router编译后chunk文件路径404问题

### ISSUE THREAD

**Issue by Kellercai** [un-pany/v3-admin-vite#9]
这个问题在vue2中也会出现，由于使用了懒加载的问题，所以用户已经在A页面使用，同时前端资源重新发布了一个新的版本，因为B页面代码有所改动导致js的hash值变化，这个时候，用户切换页面到B页面会出现资源加载404的问题。

解决：之前的解决方式是前端在router.error中判断404的问题，并主动刷新页面重新加载最新资源。个人觉得有点风险。请教一下从前端的角度有无更好的方式呢？
![image](https://user-images.githubusercontent.com/20681598/182070964-c558b43c-2f8b-4db0-acb0-7a562fce7b25.png)

**Comment by pany-ang** [comment]
暂时能想到就是你描述中的办法。其他的，比如 1. 做一套提示用户手动刷新页面的更新机制；2. 部署的时候保留旧版代码。但是实现起来的话，都要复杂许多。

**Comment by pany-ang** [comment]
如果你在 router.error 中判断后刷新页面，担心会出现无限刷新的问题。那你可以尝试一下先删除用户凭证再刷新页面，这样页面将重定向到登录页，应该能避免很多问题

**Comment by Kellercai** [comment]
> 暂时能想到就是你描述中的办法。其他的，比如 1. 做一套提示用户手动刷新页面的更新机制；2. 部署的时候保留旧版代码。但是实现起来的话，都要复杂许多。

@pany-ang 目前还是倾向于这种冒险的做法，退出登陆的话用户体验不是很好。在此基础上增加了刷新后自动跳转到目标路由的机制，保证了用户无感刷新

**Comment by 0762xiazi** [comment]
https://blog.csdn.net/Kevinblant/article/details/126237531 这个方案可以解决这个问题。
