### ISSUE TITLE
内容区全屏的时候 select 框的下拉选择没有展示

### ISSUE THREAD

**Issue by ohoherror** [un-pany/v3-admin-vite#90]

**Comment by pany-ang** [comment]
这是因为 Select 等组件的弹出层并不在 class 为 app-main 的元素里，当前 “内容区全屏” 功能示直接将 .app-main 元素进行全屏化，才导致这个问题。

等我后面换一种实现方式即可修复这个问题。

**Comment by pany-ang** [comment]
新增了 “内容区放大” 功能，不再会出现你提到的问题 
![img](https://github.com/un-pany/v3-admin-vite/assets/49087880/b1ff9f42-ad2b-4490-8990-b6449652490e)

**Comment by pany-ang** [comment]
952b327261c83b799104f5a31cba8124061aafe1 这个 commit 比较优雅的解决了这个问题
