### ISSUE TITLE
项目启动失败，控制台报错

### ISSUE THREAD

**Issue by JohnsonWang888** [un-pany/v3-admin-vite#91]
按照文档提示安装相关依赖，启动程序时会报错
Uncaught SyntaxError: Unexpected reserved word __uno.css:15 

pnpm版本是8.6.6
node版本 18.16.0
执行pnpm i 依赖安装正常，没有问题

**Comment by pany-ang** [comment]
我这边并不能复现，pnpm 和 node 版本应该是没问题的，你再确认一下。然后删除 node_modules 后重新依赖试试看。随便检查一下你的浏览器版本，我这边是最新的。

**Comment by 1zhuzhiqiang1** [comment]
应该是node版本的问题，我一开始用的node版本是16.1.0，启动报错。我换成了18.17.0可以了。另外我用的是npm，不是pnpm
