### ISSUE TITLE
设置一个详情页keepAlive缓存，打开多个详情页。关闭其中一个，其它的详情页面会刷新

### ISSUE THREAD

**Issue by weishengLi** [un-pany/v3-admin-vite#94]
例如我配置一个路由设置keepAlive为true，这里跳转详情页面会根据id的不同创建新的tag页
![image](https://github.com/un-pany/v3-admin-vite/assets/14266666/365a8ed5-9b9e-4b48-ad75-8debef010b9c)

并在页面设置相同的name
![image](https://github.com/un-pany/v3-admin-vite/assets/14266666/898d8e1b-cb6a-4fc6-bf16-9afc1368c335)

如果是点击关闭其它的页面，上面配置的这个详情页面都是正常的，切换过去并不会刷新。
但是，点击关闭 详情A页面，详情B页面 就会刷新，导致 详情B页面 之前输入的内容被清空，页面也重新加载页面、接口了。
![image](https://github.com/un-pany/v3-admin-vite/assets/14266666/9cccf9e1-8427-4d8e-925f-3a388e1c3fa3)

**Comment by pany-ang** [comment]
这种情况先自己采用其他方式缓存吧，比如 localStorage

**Comment by pany-ang** [comment]
现在系统采用的 Tag + keepAlive 的方式不好实现你所需要的需求

**Comment by pany-ang** [comment]
你可以尝试将 addCachedView 代码更改为类似这样的逻辑，看看满不满足你的需求：

```
  const addCachedView = (view: TagView) => {
    let totalByVisitedViews = 0
    let totalByCachedViews = 0
    for (let i = 0; i < visitedViews.value.length; i++) {
      if (visitedViews.value[i].name === view.name) totalByVisitedViews++
    }
    for (let i = 0; i < cachedViews.value.length; i++) {
      if (cachedViews.value[i] === view.name) totalByCachedViews++
    }
    if (typeof view.name !== "string") return
    if ((cachedViews.value.includes(view.name) && totalByVisitedViews < 2) ||totalByVisitedViews !== totalByCachedViews + 1) return
    if (view.meta?.keepAlive) cachedViews.value.push(view.name)
  }
```

但是这样的话，可能会导致你关闭其中一个详情页后再重新打开该详情页时，依旧是上一次缓存的数据，并且右键刷新也会失效

**Comment by pany-ang** [comment]
#98

**Comment by pany-ang** [comment]
方案已给出，根据你的实际情况选择其中一种即可
